// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-B-pW9Mja4221Db8KWxj3-q-8c0dnLg',
    appId: '1:597632340872:web:f8914a72934f7266ea603d',
    messagingSenderId: '597632340872',
    projectId: 'grocerygo-779f6',
    authDomain: 'grocerygo-779f6.firebaseapp.com',
    storageBucket: 'grocerygo-779f6.appspot.com',
    measurementId: 'G-499HCG4DRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72ML7sxUl29xRumpqqaC-lP2j65z0GFA',
    appId: '1:597632340872:android:a0f3aa767e4cd40eea603d',
    messagingSenderId: '597632340872',
    projectId: 'grocerygo-779f6',
    storageBucket: 'grocerygo-779f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3v7D23v0Cp2JvE3wcV5H3WzqXtk1QCWs',
    appId: '1:597632340872:ios:6c5218802228fd08ea603d',
    messagingSenderId: '597632340872',
    projectId: 'grocerygo-779f6',
    storageBucket: 'grocerygo-779f6.appspot.com',
    iosBundleId: 'com.example.grocerygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3v7D23v0Cp2JvE3wcV5H3WzqXtk1QCWs',
    appId: '1:597632340872:ios:6c5218802228fd08ea603d',
    messagingSenderId: '597632340872',
    projectId: 'grocerygo-779f6',
    storageBucket: 'grocerygo-779f6.appspot.com',
    iosBundleId: 'com.example.grocerygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ-B-pW9Mja4221Db8KWxj3-q-8c0dnLg',
    appId: '1:597632340872:web:0e287ccbe6fba6d1ea603d',
    messagingSenderId: '597632340872',
    projectId: 'grocerygo-779f6',
    authDomain: 'grocerygo-779f6.firebaseapp.com',
    storageBucket: 'grocerygo-779f6.appspot.com',
    measurementId: 'G-0KPVD6Q3D1',
  );
}
